global:
  scrape_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
  - static_configs:
    - targets: []

scrape_configs:
- job_name: prometheus
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090

- job_name: csvserver
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - csvserver:9393
